In [2]:
import numpy as np

In [6]:
a = np.random.randint(0,100,(5,10))
print(a)

[[68 74 75 35  0 17 42  5 61 21]
 [27 39 16 14 25 57 82 34 91 25]
 [26 30 72 66 48 44 25 76 86 71]
 [86 18 88  5 64 27 24 97 18 36]
 [37 98 99  6 20 34 60 90 52 43]]


In [7]:
a[2,3]

66

In [12]:
a = np.array([0,1,2,3,4,5])
print(a[:3])
print(a[3:])
print(a[::-1])

[0 1 2]
[3 4 5]
[5 4 3 2 1 0]
