In [1]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.full((5,5),"string")

array([['string', 'string', 'string', 'string', 'string'],
       ['string', 'string', 'string', 'string', 'string'],
       ['string', 'string', 'string', 'string', 'string'],
       ['string', 'string', 'string', 'string', 'string'],
       ['string', 'string', 'string', 'string', 'string']], dtype='<U6')

In [9]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.linspace(0, 40, 5)

array([ 0., 10., 20., 30., 40.])

In [13]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
np.empty(5)

array([ 0., 10., 20., 30., 40.])

In [16]:
np.random.random(20)

array([0.72141992, 0.25740924, 0.39786326, 0.48642656, 0.11684427,
       0.64824175, 0.82528144, 0.38479664, 0.28749428, 0.201911  ,
       0.20207348, 0.85035838, 0.33700964, 0.50000562, 0.35168576,
       0.900432  , 0.41403397, 0.24946304, 0.76500413, 0.53233404])

In [18]:
np.random.randint(0, 100, (3,3))

array([[ 1, 59, 68],
       [92, 89, 27],
       [ 7,  5, 20]])

## np.random.normal(20,1, ())